=== CampagneLaboratory/gobyweb2-plugins/schemas/plugins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2011  by Cornell University and the Cornell Research
  Foundation, Inc.  All Rights Reserved.

  Permission to use, copy, modify and distribute any part of GobyWeb web
  application for next-generation sequencing data alignment and analysis,
  officially docketed at Cornell as D-5061 ("WORK") and its associated
  copyrights for educational, research and non-profit purposes, without
  fee, and without a written agreement is hereby granted, provided that
  the above copyright notice, this paragraph and the following three
  paragraphs appear in all copies.

  Those desiring to incorporate WORK into commercial products or use WORK
  and its associated copyrights for commercial purposes should contact the
  Cornell Center for Technology Enterprise and Commercialization at
  395 Pine Tree Road, Suite 310, Ithaca, NY 14850;
  email:cctecconnect@cornell.edu; Tel: 607-254-4698;
  FAX: 607-254-5454 for a commercial license.

  IN NO EVENT SHALL THE CORNELL RESEARCH FOUNDATION, INC. AND CORNELL
  UNIVERSITY BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL,
  OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF
  WORK AND ITS ASSOCIATED COPYRIGHTS, EVEN IF THE CORNELL RESEARCH FOUNDATION,
  INC. AND CORNELL UNIVERSITY MAY HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
  DAMAGE.

  THE WORK PROVIDED HEREIN IS ON AN "AS IS" BASIS, AND THE CORNELL RESEARCH
  FOUNDATION, INC. AND CORNELL UNIVERSITY HAVE NO OBLIGATION TO PROVIDE
  MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.  THE CORNELL
  RESEARCH FOUNDATION, INC. AND CORNELL UNIVERSITY MAKE NO REPRESENTATIONS AND
  EXTEND NO WARRANTIES OF ANY KIND, EITHER IMPLIED OR EXPRESS, INCLUDING, BUT
  NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A
  PARTICULAR PURPOSE, OR THAT THE USE OF WORK AND ITS ASSOCIATED COPYRIGHTS
  WILL NOT INFRINGE ANY PATENT, TRADEMARK OR OTHER RIGHTS.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="T_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="CATEGORY"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="INTEGER"/>
            <xs:enumeration value="STRING"/>
            <xs:enumeration value="SWITCH"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="T_analysisType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DiffExp"/>
            <xs:enumeration value="SequenceVariants"/>
            <xs:enumeration value="Methylation"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="T_resourceConfig">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="name"/>
            <xs:element ref="version"/>
            <xs:element ref="requires" minOccurs="0"/>
            <xs:element ref="help"/>
            <xs:element ref="files" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_resource">
        <xs:sequence>
            <xs:element ref="id"/>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element ref="versionAtLeast"/>
                <xs:element ref="versionExactly"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_requires">
        <xs:sequence>
            <xs:element ref="resource" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_plugin">
        <xs:choice>
            <xs:element ref="alignerConfig"/>
            <xs:element ref="alignmentAnalysisConfig"/>
            <xs:element ref="resourceConfig"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="T_output-schema">
        <xs:sequence>
            <xs:element ref="outputFile" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_options">
        <xs:sequence>
            <xs:element ref="validation" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="option" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_option">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="dbLegacyId" minOccurs="0"/>
            <xs:element ref="name"/>
            <xs:element ref="help"/>
            <xs:element ref="required" minOccurs="0"/>
            <xs:element ref="defaultsTo" minOccurs="0"/>
            <xs:element ref="type"/>
            <xs:element ref="categories" minOccurs="0"/>
            <xs:element ref="autoFormat" minOccurs="0"/>
            <xs:element ref="flagFormat" minOccurs="0"/>
            <xs:element ref="includeSpaces" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="hiddenWhen" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_files">
        <xs:sequence>
            <xs:element ref="file" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_file">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="filename"/>
            <xs:element ref="importFromPlugin" minOccurs="0"/>
            <xs:element ref="isDirectory" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_outputFile">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="name"/>
            <xs:element ref="help"/>
            <xs:element ref="required" minOccurs="0"/>
            <xs:element ref="filename"/>
            <xs:element ref="mimeType"/>
            <xs:element ref="tableName" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_category" mixed="true">
        <xs:sequence minOccurs="0">
            <xs:element ref="id"/>
            <xs:element ref="name"/>
            <xs:element ref="value"/>
            <xs:element ref="help"/>
            <xs:element ref="dbLegacyValue" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_categories">
        <xs:sequence>
            <xs:element ref="category" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_alignmentAnalysisConfig">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="dbLegacyId" minOccurs="0"/>
            <xs:element ref="name"/>
            <xs:element ref="version"/>
            <xs:element ref="help"/>
            <xs:element ref="disabled" minOccurs="0"/>
            <xs:element ref="requires" minOccurs="0"/>
            <xs:element ref="minimumNumberOfGroups" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="maximumNumberOfGroups" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="supportsTranscriptAlignments" minOccurs="0"/>
            <xs:element ref="supportsGobyAlignments" minOccurs="0"/>
            <xs:element ref="supportsBAMAlignments" minOccurs="0"/>
            <xs:element ref="copyAlignments" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="copyWeightFiles" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="splitProcessCombine" minOccurs="0"/>
            <xs:element ref="producesVariantCallingFormatOutput" minOccurs="0"/>
            <xs:element ref="producesTabDelimitedOutput" minOccurs="0"/>
            <xs:element ref="files" minOccurs="0"/>
            <xs:element ref="outputSchema" minOccurs="0"/>
            <xs:element ref="runtime" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="execute" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="options" minOccurs="0"/>
            <xs:element ref="analysisType"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_alignerConfig">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="dbLegacyId" minOccurs="0"/>
            <xs:element ref="name"/>
            <xs:element ref="version"/>
            <xs:element ref="help"/>
            <xs:element ref="disabled" minOccurs="0"/>
            <xs:element ref="requires" minOccurs="0"/>
            <xs:element ref="supportsColorSpace" minOccurs="0"/>
            <xs:element ref="supportsBisulfiteConvertedReads" minOccurs="0"/>
            <xs:element ref="supportsGobyReads" minOccurs="0"/>
            <xs:element ref="supportsGobyAlignments" minOccurs="0"/>
            <xs:element ref="supportsBAMAlignments" minOccurs="0"/>
            <xs:element ref="supportsPairedEndAlignments" minOccurs="0"/>
            <xs:element ref="supportsFastqReads" minOccurs="0"/>
            <xs:element ref="supportsFastaReads" minOccurs="0"/>
            <xs:element ref="indexDirectory" minOccurs="0"/>
            <xs:element ref="runtime" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="execute" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="options" minOccurs="0"/>
            <xs:element ref="files" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_validation">
        <xs:sequence>
            <xs:element ref="rule" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_script">
        <xs:all>
        </xs:all>
        <xs:attribute name="filename" type="xs:string"/>
        <xs:attribute name="language" type="T_script_language_type"/>
        <xs:attribute name="phase" type="T_script_phase_type"/>
    </xs:complexType>
    <xs:element name="need" type="T_need"></xs:element>
    <xs:complexType name="T_rule">
        <xs:all>
        </xs:all>
        <xs:attribute name="validWhen" type="xs:string"/>
        <xs:attribute name="error" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_need">
        <xs:all>
        </xs:all>
        <xs:attribute name="scope" type="T_scope">
        </xs:attribute>
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_runtime">
        <xs:sequence>
            <xs:element ref="need" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_execute">
        <xs:sequence>
            <xs:element ref="script" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="T_scope">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GLOBAL"/>
            <xs:enumeration value="SPLIT_JVM"/>
            <xs:enumeration value="ALIGN"/>
            <xs:enumeration value="ALIGN_JVM"/>
            <xs:enumeration value="PROCESS"/>
            <xs:enumeration value="PROCESS_JVM"/>
            <xs:enumeration value="COMBINE"/>
            <xs:enumeration value="COMBINE_JVM"/>
            <xs:enumeration value="ALIGNMENT_POST_PROCESSING"/>
            <xs:enumeration value="ALIGNMENT_POST_PROCESSING_JVM"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="T_filename">
        <!-- make sure we don't allow spaces of newline in a filename, because IDEA tends to add them reformatting XML
        files, and this breaks the app. -->
        <xs:restriction base="xs:string">
            <xs:pattern value="[^\n\r\t\s]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="versionAtLeast" type="xs:string"/>
    <xs:element name="versionExactly" type="xs:string"/>
    <xs:element name="version" type="xs:string"/>
    <xs:element name="type" type="T_type"/>
    <xs:element name="supportsTranscriptAlignments" type="xs:boolean"/>
    <xs:element name="supportsPairedEndAlignments" type="xs:boolean"/>
    <xs:element name="supportsGobyReads" type="xs:boolean"/>
    <xs:element name="supportsGobyAlignments" type="xs:boolean"/>
    <xs:element name="copyAlignments" type="xs:boolean"  default="true"/>
    <xs:element name="copyWeightFiles" type="xs:boolean"  default="true"/>
    <xs:element name="supportsFastqReads" type="xs:boolean"/>
    <xs:element name="supportsFastaReads" type="xs:boolean"/>
    <xs:element name="supportsColorSpace" type="xs:boolean"/>
    <xs:element name="supportsBisulfiteConvertedReads" type="xs:boolean"/>
    <xs:element name="supportsBAMAlignments" type="xs:boolean"/>
    <xs:element name="splitProcessCombine" type="xs:boolean"/>
    <xs:element name="resourceConfig" type="T_resourceConfig"/>
    <xs:element name="resource" type="T_resource"/>
    <xs:element name="requires" type="T_requires"/>
    <xs:element name="required" type="xs:boolean"/>
    <xs:element name="producesVariantCallingFormatOutput" type="xs:boolean"/>
    <xs:element name="producesTabDelimitedOutput" type="xs:boolean"/>
    <xs:element name="plugin" type="T_plugin"/>
    <xs:element name="outputSchema" type="T_output-schema"/>
    <xs:element name="options" type="T_options"/>
    <xs:element name="option" type="T_option"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="mimeType" type="xs:string"/>
    <xs:element name="tableName" type="xs:string"/>
    <xs:element name="indexDirectory" type="T_filename"/>
    <xs:element name="includeSpaces" type="xs:boolean"/>
    <xs:element name="importFromPlugin" type="xs:string"/>
    <xs:element name="id" type="xs:string"/>
    <xs:element name="help" type="xs:string"/>
    <xs:element name="flagFormat" type="xs:string"/>
    <xs:element name="files" type="T_files"/>
    <xs:element name="file" type="T_file"/>
    <xs:element name="outputFile" type="T_outputFile"/>
    <xs:element name="filename" type="xs:string"/>
    <xs:element name="disabled" type="xs:boolean"/>
    <xs:element name="defaultsTo" type="xs:string"/>
    <xs:element name="dbLegacyId" type="xs:string"/>
    <xs:element name="dbLegacyValue" type="xs:string"/>
    <xs:element name="category" type="T_category"/>
    <xs:element name="categories" type="T_categories"/>
    <xs:element name="autoFormat" type="xs:boolean"/>
    <xs:element name="alignmentAnalysisConfig" type="T_alignmentAnalysisConfig"/>
    <xs:element name="alignerConfig" type="T_alignerConfig"/>
    <xs:element name="minimumNumberOfGroups" type="xs:integer"/>
    <xs:element name="maximumNumberOfGroups" type="xs:integer"/>
    <xs:element name="analysisType" type="T_analysisType"/>
    <xs:element name="hiddenWhen" type="xs:string"/>
    <xs:element name="validation" type="T_validation"/>
    <xs:element name="rule" type="T_rule"/>
    <xs:element name="runtime" type="T_runtime"/>
    <xs:element name="execute" type="T_execute"/>
    <xs:element name="isDirectory" type="T_isDirectory" default="false"/>

    <xs:element name="script" type="T_script"/>
    <xs:simpleType name="T_script_language_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="groovy"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="T_script_phase_type">
        <xs:restriction base="xs:string">
                    <xs:enumeration value="pre-deployment"/>
                </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="T_isDirectory">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

</xs:schema>

=== CampagneLaboratory/gobyweb2-plugins/plugins/aligners/GSNAP_GOBY_2011_07_07/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright (c) 2011-2012  by Cornell University  and the  Cornell Research Foundation,
  ~ Inc. All Rights Reserved.
  ~
  ~ GobyWeb plugins  are released  under the LGPL3 license,  unless  otherwise specified
  ~ by the license of a specific plugin. See the file LGPL3.license in this distribution
  ~ for a copy of the LGPL license.
  ~
  ~ When a plugin is not released under the LGPL3 license,  the comments  at the top  of
  ~ the plugin's config.xml will indicate how that specific plugin is released/licensed.
  -->
<alignerConfig xsi:noNamespaceSchemaLocation="../../../schemas/plugins.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>GSNAP (Goby output), 2011-07-07</name>
    <id>GSNAP_GOBY_2011_07_07</id>
    <help>GSNAP writing to Goby output.</help>
    <version>1.0</version>
    <disabled>true</disabled>
    <uiTemplate>Aligner</uiTemplate>
    <supportsColorSpace>false</supportsColorSpace>
    <supportsGobyAlignments>true</supportsGobyAlignments>
    <supportsPairedEndAlignments>true</supportsPairedEndAlignments>
    <supportsBAMAlignments>false</supportsBAMAlignments>
    <supportsBisulfiteConvertedReads>false</supportsBisulfiteConvertedReads>
    <supportsGobyReads>true</supportsGobyReads>
    <supportsFastqReads>false</supportsFastqReads>
    <supportsFastaReads>false</supportsFastaReads>
    <indexDirectory>%NODE_LOCAL_DATA_ROOT%/%VERSION%/%ORGANISM%/%SPACE%/gsnap</indexDirectory>
    <requires>
        <resource>
            <id>GSNAP_WITH_GOBY</id>
            <versionExactly>2011.07.07</versionExactly>
        </resource>
        <resource>
            <id>ILLUMINA_ADAPTERS</id>
            <versionAtLeast>1.0</versionAtLeast>
        </resource>
    </requires>
    <runtime>
        <need scope="ALIGN" key="excl" value="true"/>
        <need scope="ALIGN" key="h_vmem" value="25G"/>
        <need scope="ALIGN" key="virtual_free" value="28G"/>
        <need scope="ALIGN" key="os" value="rhel5.4"/>
        <need scope="ALIGN_JVM" value="4G"/>
        <need scope="ALIGNMENT_POST_PROCESSING" key="excl" value="false"/>
        <need scope="ALIGNMENT_POST_PROCESSING" key="h_vmem" value="10G" />
        <need scope="ALIGNMENT_POST_PROCESSING" key="virtual_free" value="12G" />

    </runtime>
    <options>
        <option>
            <id>ALIGNER_OPTIONS</id>
            <dbLegacyId>alignerAdvancedOptions</dbLegacyId>
            <name>Other aligner options</name>
            <help>Provide any additional GSNAP option here following the syntax expected by GSNAP.</help>
            <required>false</required>
            <defaultsTo></defaultsTo>
            <type>STRING</type>
            <flagFormat>%s</flagFormat>
            <includeSpaces>true</includeSpaces>
        </option>
        <option>
            <id>AMBIGUITY_THRESHOLD</id>
            <dbLegacyId>ambiguityThreshold</dbLegacyId>
            <name>Ambiguity threshold</name>
            <help>The maximum number of locations a read can match in the reference to not be considered ambiguous. Read
                is ambiguous if #hits>threshold.
            </help>
            <required>true</required>
            <defaultsTo>1</defaultsTo>
            <autoFormat>true</autoFormat>
            <type>INTEGER</type>
            <flagFormat>-n %s</flagFormat>
            <includeSpaces>true</includeSpaces>
        </option>
        <!-- This version doesn't support bisulfite, so no strandness option -->
    </options>
</alignerConfig>

=== CampagneLaboratory/gobyweb2-plugins/plugins/analyses/SEQUENCE_BASE_INFORMATION/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright (c) 2011-2012  by Cornell University  and the  Cornell Research Foundation,
  ~ Inc. All Rights Reserved.
  ~
  ~ GobyWeb plugins  are released  under the LGPL3 license,  unless  otherwise specified
  ~ by the license of a specific plugin. See the file LGPL3.license in this distribution
  ~ for a copy of the LGPL license.
  ~
  ~ When a plugin is not released under the LGPL3 license,  the comments  at the top  of
  ~ the plugin's config.xml will indicate how that specific plugin is released/licensed.
  -->
<alignmentAnalysisConfig xsi:noNamespaceSchemaLocation="../../../schemas/plugins.xsd"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Sequence Variation to .sbi/.sbip</name>
    <id>SEQUENCE_BASE_INFORMATION</id>
    <dbLegacyId>SEQUENCE_BASE_INFORMATION</dbLegacyId>
    <help>Produce sbi/.sbip files from Goby alignments.
    </help>
    <version>1.2</version>
    <analysisType>SequenceVariants</analysisType>
    <minimumNumberOfGroups>1</minimumNumberOfGroups>
    <maximumNumberOfGroups>10</maximumNumberOfGroups>
    <supportsTranscriptAlignments>false</supportsTranscriptAlignments>
    <splitProcessCombine>true</splitProcessCombine>
    <producesTabDelimitedOutput>true</producesTabDelimitedOutput>
    <supportsGobyAlignments>true</supportsGobyAlignments>
    <copyWeightFiles>false</copyWeightFiles>
    <requires>
        <resource>
            <id>GOBY3</id>
            <versionExactly>3.0.3.-11</versionExactly>
        </resource>
        <resource>
            <id>DLVARIATION</id>
            <versionExactly>1.0.3.-995</versionExactly>
        </resource>
        <resource>
            <id>GOBY_INDEXED_GENOMES</id>
            <versionAtLeast>1.0.1</versionAtLeast>
        </resource>
    </requires>
    <runtime>
        <need scope="GLOBAL" key="h_vmem" value="18G"/>
        <need scope="GLOBAL" key="virtual_free" value="20G"/>
        <need scope="PROCESS" key="excl" value="false"/>
        <need scope="PROCESS" key="h_vmem" value="13G"/>
        <need scope="PROCESS" key="virtual_free" value="15G"/>
        <need scope="PROCESS_JVM" value="10G"/>
        <need scope="COMBINE" key="excl" value="false"/>
        <need scope="COMBINE" key="h_vmem" value="45G"/>
        <need scope="COMBINE" key="virtual_free" value="30G"/>
        <need scope="COMBINE_JVM" value="40G"/>
        <artifacts scope="SUBMIT" required="true"/>
    </runtime>

    <options>
        <option>
            <id>OUTPUT_FORMAT</id>
            <dbLegacyId>analysisType_compare_sequence_variants</dbLegacyId>
            <name>Type of analysis and output format</name>
            <help>Determines the type of sequence variation analysis to perform and the output format.</help>
            <required>true</required>
            <defaultsTo>GENOTYPES</defaultsTo>
            <type>CATEGORY</type>
            <categories>
                <category>
                    <id>SEQUENCE_BASE_INFORMATION</id>
                    <name>sbi/sbip</name>
                    <value>SEQUENCE_BASE_INFORMATION</value>
                    <help>Produce sbi/sbip files for deep learning training.</help>
                    <dbLegacyValue>sbi_sbip</dbLegacyValue>
                </category>
            </categories>
            <autoFormat>true</autoFormat>
            <flagFormat>--format=%s</flagFormat>
            <includeSpaces>true</includeSpaces>
        </option>
        <option>
            <id>REALIGN_AROUND_INDELS</id>
            <dbLegacyId>realignment_option</dbLegacyId>
            <name>Realign reads near indels</name>
            <help>When this option is active, reads are realigned around indels and this can help prevent alignment
                artifacts.
            </help>
            <required>true</required>
            <defaultsTo>false</defaultsTo>
            <type>BOOLEAN</type>
            <autoFormat>false</autoFormat>
        </option>
        <option>
            <id>CALL_INDELS</id>
            <name>Call indels</name>
            <help>When this option is active, indels are called and reported in the VCF output file. Please be advised
                that the VCF output may become incompatible with various tools, as rules for reporting indels in VCF are
                far from clearly described and various tools are known to interpret the VCF specification differently.
            </help>
            <required>false</required>
            <defaultsTo>false</defaultsTo>
            <type>BOOLEAN</type>
            <autoFormat>false</autoFormat>
        </option>
        <option>
            <id>FORCE_DIPLOID</id>
            <name>Diploid genome</name>
            <help>When this option is active, genotype calls are forced to be diploid. Use when you know that the
                genome the reads were generated from was diploid.
            </help>
            <required>false</required>
            <defaultsTo>false</defaultsTo>
            <type>BOOLEAN</type>
            <autoFormat>false</autoFormat>
        </option>
        <option>
            <id>MINIMUM_VARIATION_SUPPORT</id>
            <name>Minimum variation support</name>
            <help>Minimum number of reads that must have the variation for the variation to be reported in the output
            </help>
            <required>true</required>
            <defaultsTo>1</defaultsTo>
            <type>INTEGER</type>
            <autoFormat>false</autoFormat>
        </option>
        <option>
            <id>THRESHOLD_DISTINCT_READ_INDICES</id>
            <name>Minimum number of distinct read indices</name>
            <help>Number of distinct read indices a position has to have to be reported in the output.</help>
            <required>true</required>
            <defaultsTo>1</defaultsTo>
            <type>INTEGER</type>
            <autoFormat>false</autoFormat>
        </option>
        <option>
            <id>RECORDS_PER_BUCKET</id>
            <name>Number of records per bucket</name>
            <help>Shuffling phase: number of records per bucket. Large bucket sizes require more memory for sorting each bucket, but require less files to complete shuffling.</help>
            <required>true</required>
            <defaultsTo>500000</defaultsTo>
            <type>INTEGER</type>
            <autoFormat>false</autoFormat>
        </option>
        <option>
            <id>RANDOM_SEED</id>
            <name>Random Seed</name>
            <help>Seed use to sample records. Only used when sampling rate is lower than 1.0.
            </help>
            <required>true</required>
            <defaultsTo>2390239</defaultsTo>
            <type>INTEGER</type>
            <autoFormat>false</autoFormat>
        </option>
        <option>
            <id>SAMPLING_RATE</id>
            <name>Sampling Rate</name>
            <help>Ratio of sites to write to output. The default writes all sites. Use 0.1 to sample 10% of sites.
            </help>
            <required>true</required>
            <defaultsTo>1.0</defaultsTo>
            <type>DOUBLE</type>
            <autoFormat>false</autoFormat>
        </option>

    </options>

    <outputSchema>
        <outputFile>
            <id>GOBY_SBI</id>
            <name>.sbi/sbip files</name>
            <required>true</required>
            <mimeType>application/goby_sbi</mimeType>
            <filename>out.sbi</filename>
            <help>View the .sbi file.
            </help>
        </outputFile>
        <!--outputFile>
            <id>SBIP</id>
            <name>.sbip (sbi properties) file</name>
            <required>true</required>
            <mimeType>text/x-java-properties</mimeType>
            <tableName>sbi</tableName>
            <filename>out.sbip</filename>
            <help>View the .sbip (properties) file.
            </help>
        </outputFile-->
    </outputSchema>
</alignmentAnalysisConfig>

=== CampagneLaboratory/gobyweb2-plugins/plugins/resources/TABIX_0.2.6/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright (c) 2011-2013  by Cornell University  and the  Cornell Research Foundation,
  ~ Inc. All Rights Reserved.
  ~
  ~ GobyWeb plugins  are released  under the LGPL3 license,  unless  otherwise specified
  ~ by the license of a specific plugin. See the file LGPL3.license in this distribution
  ~ for a copy of the LGPL license.
  ~
  ~ When a plugin is not released under the LGPL3 license,  the comments  at the top  of
  ~ the plugin's config.xml will indicate how that specific plugin is released/licensed.
  -->
<resourceConfig xsi:noNamespaceSchemaLocation="../../../schemas/plugins.xsd"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Tabix</name>
    <id>TABIX</id>
    <help>Tabix distribution. Tools for indexing tab delimited files. Auto-install with
        artifacts.
    </help>
    <version>0.2.6</version>
    <artifacts>
        <artifact id="BINARIES" order="1"/>
    </artifacts>
    <files>
        <file>
            <id>EXEC_PATH</id>
            <filename>tabix</filename>
        </file>
        <file>
            <id>BGZIP_EXEC_PATH</id>
            <filename>bgzip</filename>
        </file>
    </files>
</resourceConfig>
