=== CampagneLaboratory/gobyweb2-plugins/schemas/plugins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2011  by Cornell University and the Cornell Research
  Foundation, Inc.  All Rights Reserved.

  Permission to use, copy, modify and distribute any part of GobyWeb web
  application for next-generation sequencing data alignment and analysis,
  officially docketed at Cornell as D-5061 ("WORK") and its associated
  copyrights for educational, research and non-profit purposes, without
  fee, and without a written agreement is hereby granted, provided that
  the above copyright notice, this paragraph and the following three
  paragraphs appear in all copies.

  Those desiring to incorporate WORK into commercial products or use WORK
  and its associated copyrights for commercial purposes should contact the
  Cornell Center for Technology Enterprise and Commercialization at
  395 Pine Tree Road, Suite 310, Ithaca, NY 14850;
  email:cctecconnect@cornell.edu; Tel: 607-254-4698;
  FAX: 607-254-5454 for a commercial license.

  IN NO EVENT SHALL THE CORNELL RESEARCH FOUNDATION, INC. AND CORNELL
  UNIVERSITY BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL,
  OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF
  WORK AND ITS ASSOCIATED COPYRIGHTS, EVEN IF THE CORNELL RESEARCH FOUNDATION,
  INC. AND CORNELL UNIVERSITY MAY HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
  DAMAGE.

  THE WORK PROVIDED HEREIN IS ON AN "AS IS" BASIS, AND THE CORNELL RESEARCH
  FOUNDATION, INC. AND CORNELL UNIVERSITY HAVE NO OBLIGATION TO PROVIDE
  MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.  THE CORNELL
  RESEARCH FOUNDATION, INC. AND CORNELL UNIVERSITY MAKE NO REPRESENTATIONS AND
  EXTEND NO WARRANTIES OF ANY KIND, EITHER IMPLIED OR EXPRESS, INCLUDING, BUT
  NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A
  PARTICULAR PURPOSE, OR THAT THE USE OF WORK AND ITS ASSOCIATED COPYRIGHTS
  WILL NOT INFRINGE ANY PATENT, TRADEMARK OR OTHER RIGHTS.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="T_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="CATEGORY"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="INTEGER"/>
            <xs:enumeration value="STRING"/>
            <xs:enumeration value="SWITCH"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="T_analysisType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DiffExp"/>
            <xs:enumeration value="SequenceVariants"/>
            <xs:enumeration value="Methylation"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="T_resourceConfig">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="name"/>
            <xs:element ref="version"/>
            <xs:element ref="requires" minOccurs="0"/>
            <xs:element ref="help"/>
            <xs:element ref="files" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_resource">
        <xs:sequence>
            <xs:element ref="id"/>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element ref="versionAtLeast"/>
                <xs:element ref="versionExactly"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_requires">
        <xs:sequence>
            <xs:element ref="resource" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_plugin">
        <xs:choice>
            <xs:element ref="alignerConfig"/>
            <xs:element ref="alignmentAnalysisConfig"/>
            <xs:element ref="resourceConfig"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="T_output-schema">
        <xs:sequence>
            <xs:element ref="outputFile" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_options">
        <xs:sequence>
            <xs:element ref="validation" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="option" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_option">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="dbLegacyId" minOccurs="0"/>
            <xs:element ref="name"/>
            <xs:element ref="help"/>
            <xs:element ref="required" minOccurs="0"/>
            <xs:element ref="defaultsTo" minOccurs="0"/>
            <xs:element ref="type"/>
            <xs:element ref="categories" minOccurs="0"/>
            <xs:element ref="autoFormat" minOccurs="0"/>
            <xs:element ref="flagFormat" minOccurs="0"/>
            <xs:element ref="includeSpaces" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="hiddenWhen" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_files">
        <xs:sequence>
            <xs:element ref="file" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_file">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="filename"/>
            <xs:element ref="importFromPlugin" minOccurs="0"/>
            <xs:element ref="isDirectory" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_outputFile">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="name"/>
            <xs:element ref="help"/>
            <xs:element ref="required" minOccurs="0"/>
            <xs:element ref="filename"/>
            <xs:element ref="mimeType"/>
            <xs:element ref="tableName" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_category" mixed="true">
        <xs:sequence minOccurs="0">
            <xs:element ref="id"/>
            <xs:element ref="name"/>
            <xs:element ref="value"/>
            <xs:element ref="help"/>
            <xs:element ref="dbLegacyValue" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_categories">
        <xs:sequence>
            <xs:element ref="category" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_alignmentAnalysisConfig">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="dbLegacyId" minOccurs="0"/>
            <xs:element ref="name"/>
            <xs:element ref="version"/>
            <xs:element ref="help"/>
            <xs:element ref="disabled" minOccurs="0"/>
            <xs:element ref="requires" minOccurs="0"/>
            <xs:element ref="minimumNumberOfGroups" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="maximumNumberOfGroups" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="supportsTranscriptAlignments" minOccurs="0"/>
            <xs:element ref="supportsGobyAlignments" minOccurs="0"/>
            <xs:element ref="supportsBAMAlignments" minOccurs="0"/>
            <xs:element ref="copyAlignments" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="copyWeightFiles" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="splitProcessCombine" minOccurs="0"/>
            <xs:element ref="producesVariantCallingFormatOutput" minOccurs="0"/>
            <xs:element ref="producesTabDelimitedOutput" minOccurs="0"/>
            <xs:element ref="files" minOccurs="0"/>
            <xs:element ref="outputSchema" minOccurs="0"/>
            <xs:element ref="runtime" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="execute" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="options" minOccurs="0"/>
            <xs:element ref="analysisType"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_alignerConfig">
        <xs:all>
            <xs:element ref="id"/>
            <xs:element ref="dbLegacyId" minOccurs="0"/>
            <xs:element ref="name"/>
            <xs:element ref="version"/>
            <xs:element ref="help"/>
            <xs:element ref="disabled" minOccurs="0"/>
            <xs:element ref="requires" minOccurs="0"/>
            <xs:element ref="supportsColorSpace" minOccurs="0"/>
            <xs:element ref="supportsBisulfiteConvertedReads" minOccurs="0"/>
            <xs:element ref="supportsGobyReads" minOccurs="0"/>
            <xs:element ref="supportsGobyAlignments" minOccurs="0"/>
            <xs:element ref="supportsBAMAlignments" minOccurs="0"/>
            <xs:element ref="supportsPairedEndAlignments" minOccurs="0"/>
            <xs:element ref="supportsFastqReads" minOccurs="0"/>
            <xs:element ref="supportsFastaReads" minOccurs="0"/>
            <xs:element ref="indexDirectory" minOccurs="0"/>
            <xs:element ref="runtime" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="execute" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="options" minOccurs="0"/>
            <xs:element ref="files" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_validation">
        <xs:sequence>
            <xs:element ref="rule" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_script">
        <xs:all>
        </xs:all>
        <xs:attribute name="filename" type="xs:string"/>
        <xs:attribute name="language" type="T_script_language_type"/>
        <xs:attribute name="phase" type="T_script_phase_type"/>
    </xs:complexType>
    <xs:element name="need" type="T_need"></xs:element>
    <xs:complexType name="T_rule">
        <xs:all>
        </xs:all>
        <xs:attribute name="validWhen" type="xs:string"/>
        <xs:attribute name="error" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_need">
        <xs:all>
        </xs:all>
        <xs:attribute name="scope" type="T_scope">
        </xs:attribute>
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_runtime">
        <xs:sequence>
            <xs:element ref="need" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_execute">
        <xs:sequence>
            <xs:element ref="script" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="T_scope">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GLOBAL"/>
            <xs:enumeration value="SPLIT_JVM"/>
            <xs:enumeration value="ALIGN"/>
            <xs:enumeration value="ALIGN_JVM"/>
            <xs:enumeration value="PROCESS"/>
            <xs:enumeration value="PROCESS_JVM"/>
            <xs:enumeration value="COMBINE"/>
            <xs:enumeration value="COMBINE_JVM"/>
            <xs:enumeration value="ALIGNMENT_POST_PROCESSING"/>
            <xs:enumeration value="ALIGNMENT_POST_PROCESSING_JVM"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="T_filename">
        <!-- make sure we don't allow spaces of newline in a filename, because IDEA tends to add them reformatting XML
        files, and this breaks the app. -->
        <xs:restriction base="xs:string">
            <xs:pattern value="[^\n\r\t\s]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="versionAtLeast" type="xs:string"/>
    <xs:element name="versionExactly" type="xs:string"/>
    <xs:element name="version" type="xs:string"/>
    <xs:element name="type" type="T_type"/>
    <xs:element name="supportsTranscriptAlignments" type="xs:boolean"/>
    <xs:element name="supportsPairedEndAlignments" type="xs:boolean"/>
    <xs:element name="supportsGobyReads" type="xs:boolean"/>
    <xs:element name="supportsGobyAlignments" type="xs:boolean"/>
    <xs:element name="copyAlignments" type="xs:boolean"  default="true"/>
    <xs:element name="copyWeightFiles" type="xs:boolean"  default="true"/>
    <xs:element name="supportsFastqReads" type="xs:boolean"/>
    <xs:element name="supportsFastaReads" type="xs:boolean"/>
    <xs:element name="supportsColorSpace" type="xs:boolean"/>
    <xs:element name="supportsBisulfiteConvertedReads" type="xs:boolean"/>
    <xs:element name="supportsBAMAlignments" type="xs:boolean"/>
    <xs:element name="splitProcessCombine" type="xs:boolean"/>
    <xs:element name="resourceConfig" type="T_resourceConfig"/>
    <xs:element name="resource" type="T_resource"/>
    <xs:element name="requires" type="T_requires"/>
    <xs:element name="required" type="xs:boolean"/>
    <xs:element name="producesVariantCallingFormatOutput" type="xs:boolean"/>
    <xs:element name="producesTabDelimitedOutput" type="xs:boolean"/>
    <xs:element name="plugin" type="T_plugin"/>
    <xs:element name="outputSchema" type="T_output-schema"/>
    <xs:element name="options" type="T_options"/>
    <xs:element name="option" type="T_option"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="mimeType" type="xs:string"/>
    <xs:element name="tableName" type="xs:string"/>
    <xs:element name="indexDirectory" type="T_filename"/>
    <xs:element name="includeSpaces" type="xs:boolean"/>
    <xs:element name="importFromPlugin" type="xs:string"/>
    <xs:element name="id" type="xs:string"/>
    <xs:element name="help" type="xs:string"/>
    <xs:element name="flagFormat" type="xs:string"/>
    <xs:element name="files" type="T_files"/>
    <xs:element name="file" type="T_file"/>
    <xs:element name="outputFile" type="T_outputFile"/>
    <xs:element name="filename" type="xs:string"/>
    <xs:element name="disabled" type="xs:boolean"/>
    <xs:element name="defaultsTo" type="xs:string"/>
    <xs:element name="dbLegacyId" type="xs:string"/>
    <xs:element name="dbLegacyValue" type="xs:string"/>
    <xs:element name="category" type="T_category"/>
    <xs:element name="categories" type="T_categories"/>
    <xs:element name="autoFormat" type="xs:boolean"/>
    <xs:element name="alignmentAnalysisConfig" type="T_alignmentAnalysisConfig"/>
    <xs:element name="alignerConfig" type="T_alignerConfig"/>
    <xs:element name="minimumNumberOfGroups" type="xs:integer"/>
    <xs:element name="maximumNumberOfGroups" type="xs:integer"/>
    <xs:element name="analysisType" type="T_analysisType"/>
    <xs:element name="hiddenWhen" type="xs:string"/>
    <xs:element name="validation" type="T_validation"/>
    <xs:element name="rule" type="T_rule"/>
    <xs:element name="runtime" type="T_runtime"/>
    <xs:element name="execute" type="T_execute"/>
    <xs:element name="isDirectory" type="T_isDirectory" default="false"/>

    <xs:element name="script" type="T_script"/>
    <xs:simpleType name="T_script_language_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="groovy"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="T_script_phase_type">
        <xs:restriction base="xs:string">
                    <xs:enumeration value="pre-deployment"/>
                </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="T_isDirectory">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

</xs:schema>

=== CampagneLaboratory/gobyweb2-plugins/plugins/resources/ANNOTATE_VCF/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright (c) 2011-2013  by Cornell University  and the  Cornell Research Foundation,
  ~ Inc. All Rights Reserved.
  ~
  ~ GobyWeb plugins  are released  under the LGPL3 license,  unless  otherwise specified
  ~ by the license of a specific plugin. See the file LGPL3.license in this distribution
  ~ for a copy of the LGPL license.
  ~
  ~ When a plugin is not released under the LGPL3 license,  the comments  at the top  of
  ~ the plugin's config.xml will indicate how that specific plugin is released/licensed.
  -->
<resourceConfig xsi:noNamespaceSchemaLocation="../../../schemas/plugins.xsd"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Annotate VCF</name>
    <id>ANNOTATE_VCF</id>
    <help>Annotate VCF files with results from Variant Effect Predictor</help>
    <version>1.1</version>
    <requires>
        <resource>
            <id>VARIANT_EFFECT_PREDICTOR</id>
            <versionAtLeast>2.8</versionAtLeast>
        </resource>
        <resource>
            <id>ENSEMBL_ANNOTATIONS</id>
            <versionAtLeast>1.0</versionAtLeast>
        </resource>
        <resource>
            <id>TABIX</id>
            <versionAtLeast>0.2.6</versionAtLeast>
        </resource>
        <!--resource>
            <id>VCF_TOOLS</id>
            <versionAtLeast>0.1.10</versionAtLeast>
        </resource-->

    </requires>
    <files>
        <file>
            <id>EXEC_PATH</id>
            <filename>annotate_vcf.sh</filename>
        </file>
    </files>

</resourceConfig>

=== CampagneLaboratory/gobyweb2-plugins/plugins/resources/JRI_0.5-0/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright (c) 2011-2014  by Cornell University  and the  Cornell Research Foundation,
  ~ Inc. All Rights Reserved.
  ~
  ~ GobyWeb plugins  are released  under the LGPL3 license,  unless  otherwise specified
  ~ by the license of a specific plugin. See the file LGPL3.license in this distribution
  ~ for a copy of the LGPL license.
  ~
  ~ When a plugin is not released under the LGPL3 license,  the comments  at the top  of
  ~ the plugin's config.xml will indicate how that specific plugin is released/licensed.
  -->
<resourceConfig xsi:noNamespaceSchemaLocation="../../../schemas/plugins.xsd"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>RJava with JRI</name>
    <id>RJAVA</id>
    <help>RJava and JRI. Auto-install with artifacts.</help>
    <version>0.9.6</version>
    <requires>
        <resource>
            <id>R</id>
            <versionAtLeast>2.15.3.2</versionAtLeast>
        </resource>
    </requires>
    <artifacts>
        <artifact id="BINARIES" order="1"/>
    </artifacts>

</resourceConfig>

=== CampagneLaboratory/gobyweb2-plugins/plugins/resources/BOWTIE_2_2.0.0.5/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright (c) 2011-2012  by Cornell University  and the  Cornell Research Foundation,
  ~ Inc. All Rights Reserved.
  ~
  ~ GobyWeb plugins  are released  under the LGPL3 license,  unless  otherwise specified
  ~ by the license of a specific plugin. See the file LGPL3.license in this distribution
  ~ for a copy of the LGPL license.
  ~
  ~ When a plugin is not released under the LGPL3 license,  the comments  at the top  of
  ~ the plugin's config.xml will indicate how that specific plugin is released/licensed.
  -->
<resourceConfig xsi:noNamespaceSchemaLocation="../../../schemas/plugins.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Bowtie 2</name>
    <id>BOWTIE2</id>
    <help>Bowtie 2 short read aligner. See http://bowtie-bio.sourceforge.net/index.shtml.</help>
    <version>2.0.0.5</version>
    <files>
        <file>
            <id>EXEC_PATH</id>
            <filename>bowtie2</filename>
        </file>
        <file>
    		<id>ALIGN</id>
    		<filename>bowtie2-align</filename>
    	</file>
    	<file>
    		<id>INSPECT</id>
    		<filename>bowtie2-inspect</filename>
    	</file>
    	<file>
    		<id>BUILD</id>
    		<filename>bowtie2-build</filename>
    	</file>
    </files>
</resourceConfig>

=== CampagneLaboratory/gobyweb2-plugins/plugins/analyses/SEQ_VAR_SAMTOOLS/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright (c) 2011-2012  by Cornell University  and the  Cornell Research Foundation,
  ~ Inc. All Rights Reserved.
  ~
  ~ GobyWeb plugins  are released  under the LGPL3 license,  unless  otherwise specified
  ~ by the license of a specific plugin. See the file LGPL3.license in this distribution
  ~ for a copy of the LGPL license.
  ~
  ~ When a plugin is not released under the LGPL3 license,  the comments  at the top  of
  ~ the plugin's config.xml will indicate how that specific plugin is released/licensed.
  -->
<alignmentAnalysisConfig xsi:noNamespaceSchemaLocation="../../../schemas/plugins.xsd"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Sequence Variation Analyses with samtools</name>
    <id>SEQ_VAR_SAMTOOLS</id>
    <dbLegacyId>samtools mpileup</dbLegacyId>
    <help>Compares groups of samples and produce output about sequence variants observed in the alignments. Implemented
        with SAMTOOLS. Specific analysis depends on selected output format.
    </help>
    <version>1.0</version>
    <analysisType>SequenceVariants</analysisType>
    <minimumNumberOfGroups>1</minimumNumberOfGroups>
    <maximumNumberOfGroups>2</maximumNumberOfGroups>
    <supportsTranscriptAlignments>false</supportsTranscriptAlignments>
    <supportsBAMAlignments>true</supportsBAMAlignments>
    <splitProcessCombine>true</splitProcessCombine>
    <producesVariantCallingFormatOutput>true</producesVariantCallingFormatOutput>
    <copyWeightFiles>false</copyWeightFiles>
    <requires>
        <resource>
            <id>SAMTOOLS</id>
            <versionAtLeast>0.1.14</versionAtLeast>
        </resource>
        <resource>
            <id>ANNOTATE_VCF</id>
            <versionAtLeast>1.0</versionAtLeast>
        </resource>
    </requires>
    <runtime>
        <need scope="GLOBAL" key="h_vmem" value="18g"/>
        <need scope="GLOBAL" key="virtual_free" value="20g"/>
        <need scope="PROCESS" key="excl" value="true"/>
        <need scope="PROCESS" key="h_vmem" value="25g"/>
        <need scope="PROCESS" key="virtual_free" value="25g"/>
        <need scope="PROCESS_JVM" value="4g"/>
        <need scope="COMBINE" key="excl" value="false"/>
        <need scope="COMBINE" key="h_vmem" value="22g"/>
        <need scope="COMBINE" key="virtual_free" value="22g"/>
        <need scope="COMBINE_JVM" value="20g"/>
    </runtime>
    <options>
        <option>
            <id>OUTPUT_FORMAT</id>
            <dbLegacyId>analysisType_samtools_mpileup</dbLegacyId>
            <name>Type of analysis and output format</name>
            <help>Determines the type of sequence variation analysis to perform and the output format.</help>
            <required>true</required>
            <defaultsTo>GENOTYPES</defaultsTo>
            <type>CATEGORY</type>
            <categories>
                <category>
                    <id>GENOTYPES</id>
                    <name>genotypes</name>
                    <value>GENOTYPES</value>
                    <help>Calls genotypes at observed bases.</help>
                    <dbLegacyValue>genotypes</dbLegacyValue>
                </category>
                <category>
                    <id>GROUP_COMPARISONS</id>
                    <name>group_comparisons</name>
                    <value>GROUP_COMPARISONS</value>
                    <help>Compare groups of samples with allelic association test.</help>
                    <dbLegacyValue>group-comparison</dbLegacyValue>
                </category>
            </categories>
            <autoFormat>false</autoFormat>
        </option>
        <option>
            <id>ANNOTATE_VARIATIONS</id>
            <name>Annotate variations</name>
            <help>When this option is active, annotate variations with the Variant Effect Predictor. Not that positions
                that cannot be annotated may be removed from the output.
            </help>
            <required>true</required>
            <defaultsTo>true</defaultsTo>
            <type>BOOLEAN</type>
        </option>
        <option>
            <id>NUM_TOP_HITS</id>
            <name>Number of top hits</name>
            <help>Number of hits to report if no candidates has an adjusted p-value above the q-value threshold.</help>
            <required>true</required>
            <defaultsTo>10000</defaultsTo>
            <type>INTEGER</type>
            <autoFormat>false</autoFormat>
        </option>
    </options>

</alignmentAnalysisConfig>

=== CampagneLaboratory/gobyweb2-plugins/plugins/resources/GOBYWEB_SERVER_SIDE_2.2/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~ Copyright (c) 2011-2012  by Cornell University  and the  Cornell Research Foundation,
  ~ Inc. All Rights Reserved.
  ~
  ~ GobyWeb plugins  are released  under the LGPL3 license,  unless  otherwise specified
  ~ by the license of a specific plugin. See the file LGPL3.license in this distribution
  ~ for a copy of the LGPL license.
  ~
  ~ When a plugin is not released under the LGPL3 license,  the comments  at the top  of
  ~ the plugin's config.xml will indicate how that specific plugin is released/licensed.
  -->
<resourceConfig xsi:noNamespaceSchemaLocation="../../../schemas/plugins.xsd"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>GobyWeb server side tools</name>
    <id>GOBYWEB_SERVER_SIDE</id>
    <help>Server side tools used by many GobyWeb plugins.</help>
    <version>2.2</version>
    <requires>
        <resource>
            <id>GROOVY</id>
            <versionAtLeast>2.0.6</versionAtLeast>
        </resource>
        <resource>
            <id>FETCH_URL</id>
            <versionAtLeast>1.2</versionAtLeast>
        </resource>
    </requires>
    <files>
        <file>
            <id>ICB_GROOVY_SUPPORT_JAR</id>
            <filename>icb-groovy-support.jar</filename>
        </file>
        <file>
            <id>DEPENDENCIES_JAR</id>
            <filename>serverside-dependencies.jar</filename>
        </file>
        <file>
            <id>ARTIFACTS_SCRIPT</id>
            <filename>artifacts.sh</filename>
        </file>
        <file>
            <id>GLOBAL_GOBY_JAR</id>
            <filename>global_goby.jar</filename>
        </file>
        <file>
            <id>LOG4J_PROPERTIES</id>
            <filename>log4j.properties</filename>
        </file>
        <file>
            <id>FILESET_JAR</id>
            <filename>filesets.jar</filename>
        </file>
        <file>
            <id>ARTIFACTS_MANAGER_JAR</id>
            <filename>artifact-manager.jar</filename>
        </file>
        <file>
            <id>ARTIFACTS_MANAGER_JAR</id>
            <filename>artifact-manager.sh</filename>
        </file>
        <file>
            <id>QUEUE_WRITER</id>
            <filename>QueueWriter.groovy</filename>
        </file>
        <file>
            <id>QUEUE_WRITER_WRAPPER</id>
            <filename>queue-writer.sh</filename>
        </file>
        <file>
            <id>TSV_VCF_TO_SQLITE</id>
            <filename>TsvVcfToSqlite.groovy</filename>
        </file>
        <file>
            <id>PROCESS_SAMPLES</id>
            <filename>ProcessSamples.groovy</filename>
        </file>

    </files>
</resourceConfig>
